config/routes.rb
Rails.application.routes.draw do
  get '/index', to: 'firstrail#index'
  get '/aboutme', to: 'firstrail#aboutme'
  get '/contactme', to: 'firstrail#contactme'
  get '/technology', to: 'firstrail#technology'
  get '/home', to: 'firstrail#home'
  get '/game/2048', to: 'game1#index'
  get '/game/2548', to: 'game2#index'
  get '/game/color_flood', to: 'game3#index'

  

  resources :blogs do 
    resources :comments
  end
  # The priority is based upon order o Fcreation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  root 'firstrail#home'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/blog.rb
class Blog < ActiveRecord::Base
	has_many :comments
	validates :title,presence: true,length: {minimum:5}
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :blog
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	http_basic_authenticate_with name: "aa", password: "aa", except: [:index, :show]
	def new
		@blog=Blog.new
	end
	def index
		@blog=Blog.all
	end
	def create
		@blog=Blog.new(blog_params);
		if @blog.save
			redirect_to @blog
		else
			render 'new'
		end 
	end
	def edit
		@blog=Blog.find(params[:id])
	end
	def destroy
		@blog=Blog.find(params[:id])
		@blog.destroy
		redirect_to blogs_path
	end
	def update
		@blog=Blog.find(params[:id])
		if @blog.update(blog_params)
			redirect_to @blog
		else
			render 'edit'
		end
	end
	def show
		@blog=Blog.find(params[:id])
	end
	private
	def blog_params
		params.require(:blog).permit(:title,:body)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
	def create
    @blog = Blog.find(params[:blog_id])
    @comment = @blog.comments.create(comment_params)
    redirect_to blog_path(@blog)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:name, :body)
    end
end

app/controllers/firstrail_controller.rb
class FirstrailController < ApplicationController
	def index
	end
	def aboutme
	end
	def home
	end
	def contactme
	end
end

app/controllers/game1_controller.rb
class Game1Controller < ApplicationController
end

app/controllers/game2_controller.rb
class Game2Controller < ApplicationController
end

app/controllers/game3_controller.rb
class Game3Controller < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/firstrail_helper.rb
module FirstrailHelper
end

app/helpers/game1_helper.rb
module Game1Helper
end

app/helpers/game2_helper.rb
module Game2Helper
end

app/helpers/game3_helper.rb
module Game3Helper
end

app/views/blogs/edit.html.erb
<div class="pageindex1"><br /><br />

<h1>Editing article</h1>
 
<%= form_for :blog, url: blog_path(@blog), method: :patch do |f| %>
 
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@blog.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @blog.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <b><%= f.label :title %></b><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <b><%= f.label :body %></b><br>
    <%= f.text_area :body %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/home.html.erb
<div id="middle">
<p id="circle"><br>WEB DEVELOPMENT and MAINTENENCE</p>
<p id="circle"><br>COMMUNITY DETECTION IN SOCIAL NETWORKS</p>
<p id="circle"><br>COMPUTER DEPARTMENT</p>
<p style="width:25%;margin-left:80px;border-width:5px;border-color:black;margin-top:50px;padding-left:100px">
<b>OBJECTIVE</b>-An online Computer Science Department web portal for Teacher and student interaction.
<br>
<b>LOCATION</b>-HPES, Noida<br>
<b>TOOLS -</b><br>
<b>Server Side:</b> ASP.NET with C#.<br>
<b>Client Side:</b> HTML,CSS.<br>
<b>Database:</b> SQL Server 2005.<br>
<b>DURATION-</b> June-July, 2013<br>
</p>
<p style="width:25%;margin-left:80px;border-width: 5px;border-color: black;margin-top:50px;padding-left:100px">
<b>OBJECTIVE-</b>To understand various interactions among the group of persons in that community and with others.
<br>
<b>LOCATION-</b>IIT Guwahati<br>
<b>TOOLS -</b><br>
Python.<br>
<b>DURATION-</b> June-July, 2014<br>
</p>
<p style="width:25%;margin-left:80px;border-width: 5px;border-color: black;margin-top:50px;padding-left:100px">
<b>OBJECTIVE-</b>An online Computer Science Department web portal for Teacher and student interaction.<br>
<b>LOCATION-</b>HPES, Noida<br>
<b>TOOLS -</b><br>
<b>Server Side:</b> ASP.NET with C#.<br>
<b>Client Side:</b> HTML,CSS.<br>
<b>Database:</b> SQL Server 2005.<br>
<b>DURATION- </b>June-July, 2013<br>
</p>
</div>

app/views/blogs/index.html.erb
<div class="pageindex">
<table>
	<tr>
		<td class="intable"><h1>Title</h1></td>
		<td class="intable"><h1>Body</h1></td>
	</tr>
	<% @blog.each do |blog|%>
	<tr>
		<td class="intable"><%= blog.title%></td>
		<td class="intable"><%= blog.body%></td>
		<td class="intable"><%= link_to 'Show',blog_path(blog)%></td>
		<td class="intable"><%= link_to 'Edit',edit_blog_path(blog)%></td>
		<td class="intable"><%= link_to 'Destroy', blog_path(blog),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
	</tr>
	<%end%>
	<tr>
		<td class="intable"><%= link_to 'New',new_blog_path %></td>
		<td></td>
	</tr>
</table>
</div>

app/views/blogs/new.html.erb
<%= form_for :blog,url: blogs_path do |f|%>
<% if @blog and @blog.errors.any? %>
<div id="error_explanation">
	<h2>
        <%= pluralize(@blog.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @blog.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <%end%>
<p>
<%= f.label :title %>
<%= f.text_field :title %>
</p>
<p>
	<%= f.label :body %>
	<%= f.text_area :body %>
	</p>
	<%= f.submit %>
<%end%>

app/views/blogs/show.html.erb
<div class="pageindex"><br /><br />
<p>
	<strong>Title</strong>&nbsp;&nbsp;&nbsp;&nbsp;
	<%= @blog.title%>
</p>
<p>
	<strong>Body</strong>&nbsp;&nbsp;&nbsp;&nbsp;
	<%= @blog.body%>
</p>
<h2>Comments</h2>
<% @blog.comments.each do |comment| %>
  <p>Name:</strong>
    <%= comment.name %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% end %>
<%= form_for([@blog, @blog.comments.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>
</div>

app/views/comments/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @blog.body %>
</p>
 
<h2>Add a comment:</h2>
<%= form_for([@blog, @blog.comments.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blog_path %>

app/views/firstrail/aboutme.html.erb
<div id="top">
	<div style="float:left;width50%">
<img id="img1" src="https://scontent-sin1-1.xx.fbcdn.net/hphotos-xpf1/v/t1.0-9/11054502_728970583886618_370725838487420951_n.jpg?oh=fce05f1abb155c22913ab848a82f4a30&oe=565DAC59" width=500 height=500/></div>
<div id="innerdiv"><b>Introduction-</b>
My name is Ekansh Sharma .I have completed my B.Tech from NIT Arunachal Pradesh in CSE stream with an aggregate of 84.3 in 2015.I am looking for a Software Developer position in some reputed organisation.which can help me in enhancing my skills and provide platform to show with my given abilities and dedication towards the work.
<br ><br >
My area of interest are:DataStructure,Algorithm,DataBase,Operating System.
-I have worked on MS Sql Server 2005, Visual Studio 2010 in my training project that was based on    Development and Maintenance of the website.
<br ><br >
<b>
- I have a good knowledge of Java, C, C# and python.<br >
- I did 6 week internship from IIT Guwahati.<br >
- Secured First Place in the event Code-Wizard at Addoveddi 2014.<br >
- Secured First Place in the Web Site Design Competition.<br >
- Secured Third Place in the event Code-Wizard at Addoveddi 2013.<br >
</b>
</div>
</div>

app/views/firstrail/contactme.html.erb
<div id="bottom">
<form method=get class="form">
		<div class="last">
			<div style="float:left;width:45%;margin-left:80px">
				<p style="font-size:40px">01/GET IN<br>TOUCH</p>
				<p style="margin-top:20px">
			I would love to speak to you.Feel free to call,send us an email,<br>Tweet us or simply complete the enquiry form.</p>
			<p style="margin-top:20px">
			<img class="fimg" src="/assets/name-clipart-name-sign-md.png" style="height:80px">Ekansh Sharma<br>
			<img class="fimg" src="/assets/iphone4-mini-white-02.png" style="height:80px">+917308099461<br>
			<img class="fimg" src="/assets/raphael_mail_flat-circle-white-on-green-gradient_512x512.png" style="height:80px">ekanshsharmacse11@gmail.com<br>
			<img class="fimg" src="/assets/messages.png" style="height:80px"><br></p>
		</div>
			<!--<center>-->
		<div class="div" style="width:45%;float:left">
			<p style="font-size:40px">02/SEND ME A<br>MESSAGE</p>
			<p style="margin-top:20px">
		<input type="text" id="name" style="height:30px;width:150px;color:green" placeholder="Your Name"/>
		<br><br><br>
		<input type="text" id="phone" style="height:30px;width:150px;color:green" placeholder="+917308099461"/>
		<br /><br><br>
		<input type="text" id="email" style="height:30px;width:150px;color:green" placeholder="Email Address"/>
		<br /><br><br>
		<textarea id="comment" rows=5 cols=50 placeholder="Your Message;color:green"></textarea>
		<br /><br><br>
	<br />
		<input type=submit id="submit" style="height:60px;width:150px;font-size:40px;background-color:black;color:white" ></p>
	<!--</center>-->
</div>
	</div>

app/views/firstrail/home.html.erb
<div id="middle">
<p id="circle"><br>WEB DEVELOPMENT and MAINTENENCE</p>
<p id="circle"><br>COMMUNITY DETECTION IN SOCIAL NETWORKS</p>
<p id="circle"><br>COMPUTER DEPARTMENT</p>
<p class="move" style="width:20%;margin-left:100px;border-width:5px;border-color:black;margin-top:50px">
<b>OBJECTIVE</b>-An online Computer Science Department web portal for Teacher and student interaction.
<br>
<b>LOCATION</b>-HPES, Noida<br>
<b>TOOLS -</b><br>
<b>Server Side:</b> ASP.NET with C#.<br>
<b>Client Side:</b> HTML,CSS.<br>
<b>Database:</b> SQL Server 2005.<br>
<b>DURATION-</b> June-July, 2013<br>
</p>
<p class="move" style="width:20%;margin-left:80px;border-width:5px;border-color: black;margin-top:50px">
<b>OBJECTIVE-</b>To understand various interactions among the group of persons in that community and with others.
<br>
<b>LOCATION-</b>IIT Guwahati<br>
<b>TOOLS -</b><br>
Python.<br>
<b>DURATION-</b> June-July, 2014<br>
</p>
<p class="move" style="width:20%;margin-left:100px;border-width:5px;border-color: black;margin-top:50px">
<b>OBJECTIVE-</b>An online Computer Science Department web portal for Teacher and student interaction.<br>
<b>LOCATION-</b>HPES, Noida<br>
<b>TOOLS -</b><br>
<b>Server Side:</b> ASP.NET with C#.<br>
<b>Client Side:</b> HTML,CSS.<br>
<b>Database:</b> SQL Server 2005.<br>
<b>DURATION- </b>June-July, 2013<br>
</p>
</div>

app/views/firstrail/index.html.erb
<h1>This is home.</h1>

app/views/firstrail/technology.html.erb
<div id="topmiddle">
<h1 style="text-align:center;color:black;margin-top:50px">Technologies in which I have worked.</h1>
<p class="newclass1" style="float:left;padding-left: 100px"><img class="img" src="/assets/ASP.NET_.png" width=200 height=200/></p>
<p class="newclass1" style="float:left;padding-left: 100px"><img class="img" src="/assets/Advantages,P20of,P20DBMS.jpg.pagespeed.ce.w7czTcu4ZV.jpg" width="200px" height="200px"/></p>
<p class="newclass1" style="float:left;padding-left: 100px"><img class="img" src="/assets/html.jpg" width=200 height=200/></p>
<p class="newclass1" style="float:left;padding-left: 100px"><img class="img" src="/assets/css.gif" width=200 height=200/></p>
<p class="newclass1" style="float:left;padding-left: 100px"><img class="img" src="/assets/jquery.png" width=200 height=200/></p>
<p class="newclass1" style="float:left;padding-left: 100px"><img class="img" src="/assets/SR2hUhQN_400x400.png" width=200 height=200/></p>
<p class="newclass1" style="float:left;padding-left: 100px"><img class="img" src="/assets/speech-balloon-orange-c-icon.png" width=200 height=200/></p>
<p class="newclass1" style="float:left;padding-left: 100px"><img class="img" src="/assets/product-development-using-java.jpg" width=200 height=200/></p>


<p class="newclass"  style="float:left;padding-left: 100px"><img class="img" src="/assets/csharp-logo.png" width=200 height=200/></p>
<p class="newclass"  style="float:left;padding-left: 100px"><img class="img" src="/assets/Ruby_on_Rails.svg.png" width=200 height=200/></p>
<p class="newclass"  style="float:left;padding-left: 100px"><img class="img" src="/assets/python.jpg" width=200 height=200/></p>
<p class="newclass" style="float:left;padding-left: 100px"><img class="img" src="/assets/data_structure_by_kotsengkuba-d3vew36.jpg" width=200 height=200/></p>
<p class="newclass" style="float:left;padding-left: 100px"><img class="img" src="/assets/storage_operating_systems.jpg" width=200 height=200/></p>
<p class="newclass" style="float:left;padding-left: 100px"><img class="img" src="/assets/cs161logo.png" width=200 height=200/></p>

<div ><button id="button" style="position:static;width:100;height:50;font-size:20;background-color:color:brown;border-size:0;color:white">More...</button></div>
</div>

app/views/game1/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>2048</title>

  

  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, target-densitydpi=160dpi, initial-scale=1.0, maximum-scale=1, user-scalable=no, minimal-ui">
</head>
<body>
  <div class="container">
    <div class="heading">
      <h1 class="title">2048</h1>
      <div class="scores-container">
        <div class="score-container">0</div>
        <div class="best-container">0</div>
      </div>
    </div>

    <div class="above-game">
      <p class="game-intro">Join the numbers and get to the <strong>2048 tile!</strong></p>
      <a class="restart-button">New Game</a>
    </div>

    <div class="game-container">
      <div class="game-message">
        <p></p>
        <div class="lower">
	        <a class="keep-playing-button">Keep going</a>
          <a class="retry-button">Try again</a>
        </div>
      </div>

      <div class="grid-container">
        <div class="grid-row">
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
        </div>
        <div class="grid-row">
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
        </div>
        <div class="grid-row">
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
        </div>
        <div class="grid-row">
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
        </div>
      </div>

      <div class="tile-container">

      </div>
    </div>

    <p class="game-explanation">
      <center><a href="https://ekansh-sharma.github.io" class="btn btn-success">HOME</a></center><br />
      <strong class="important">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same number touch, they <strong>merge into one!</strong>
    </p>
    <hr>
  </div>
</body>
</html>

app/views/game2/index.html.erb
<!DOCTYPE html>
<html>

<body>
  <div class="container" >
    <div class="heading">
      <h1 class="title">2548</h1>
      <div class="scores-container">
        <div class="score-container">0</div>
        <div class="best-container">0</div>
      </div>
    </div>

    <div class="above-game">
      <p class="game-intro">Join the numbers and get to the <strong>2548 tile!</strong></p>
      <a class="restart-button">New Game</a>
    </div>

    <div class="game-container">
      <div class="game-message">
        <p></p>
        <div class="lower">
	        <a class="keep-playing-button">Keep going</a>
          <a class="retry-button">Try again</a>
        </div>
      </div>

      <div class="grid-container">
        <div class="grid-row">
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
        </div>
        <div class="grid-row">
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
        </div>
        <div class="grid-row">
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
        </div>
        <div class="grid-row">
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
        </div>
      </div>

      <div class="tile-container">

      </div>
    </div>

    <p class="game-explanation">
      <p><a></a></p>
        <center><a href="https://ekansh-sharma.github.io" class="btn btn-success">HOME</a></center><br />
        <strong class="important">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same number touch, they <strong>merge into one!</strong>
    </p>
    <hr>
  </div>
</body>
</html>

app/views/game3/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>2048</title>
  
  <style type="text/css">
.piece {
    width: 28px;
    height: 30px;
    border:0px;
}
.button {
    width: 25px;
    height: 30px;
    border:0px;
    background-image:url(circle.gif);
}
.red {
background-color: red;
}
.yellow {
background-color: yellow;
}
.green {
background-color: #0F0;
}
.blue {
background-color: blue;
}
.purple {
background-color: purple;
}
.pink {
background-color: fuchsia;
}
#game-table {
    margin:0px;
    border:0px;
    padding: 0px;
    border-spacing:0px;
}
#button-table {
    border-spacing:4px;
    vertical-align: top;
}
#turn-counter {
    font-family: sans-serif;
}
</style>
</head>
<body>
  
  <div class="container">
    <div class="heading">
      <h1 class="title">Colour flood</h1>
      <div class="scores-container">
        <div class="score-container">0</div>
        <div class="best-container">0</div>
      </div>
    </div>

    <div class="above-game">
      <p class="game-intro">Join the numbers and get to the <strong>Colour flood.</strong></p>
      <a class="restart-button" onclick="new_game()">New Game</a>
    </div>
    <center>
<table>
    
  <tr>
    <td valign="top">
      
    </td>
    <td>
        <div class="well">
      <table id="game-table">
        <!-- Internet Explorer insists that this must be tbody.
             See Dynamically created tables in Internet Explorer. -->
        <tbody id="game-table-tbody">
        </tbody>
      </table>
      </div>
    </td>
    
  </tr>
  <tr><td>
    <td></tr>
</table></center>
<br /><br />
<div><center><table>
        <tr>
            <td></td>
            <tr>
          <td valign="top">
            <table id="button-table">
              <tr>
                <td class="button blue" onclick="flood ('blue')">
                </td>
                <td class="button red" onclick="flood ('red')">
                </td>
                <td class="button green" onclick="flood ('green')">
                </td>
                <td class="button yellow" onclick="flood ('yellow')">
                </td>
                <td class="button pink" onclick="flood ('pink')">
                </td>
                <td class="button purple" onclick="flood ('purple')">
                </td>
              </tr>
              
            </table>
          </td>
        </tr>
        <tr valign="top">
          <td id="turn-counter" valign="top">
            Turn: <span id="moves"></span>/<span id="max-moves"></span>
          </td>
        </tr>
        <tr valign="top">
          <td valign="top">
            <input type="submit" value="Help" onclick="help ()">
          </td>
        </tr>
<!--
        <tr valign="top">
          <td valign="top">
            <input type="submit" value="Solve" onclick="solve ()">
          </td>
        </tr>
-->
      </table></center></div>
    <script type="text/javascript">
    debugger
  </script>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirstRails</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'game3' %>
  <%= javascript_include_tag 'js/classlist_polyfill' %>
  <%= javascript_include_tag 'js/animframe_polyfill' %>
  <%= javascript_include_tag 'js/keyboard_input_manager' %>
  <%= javascript_include_tag 'js/html_actuator' %>
  <%= javascript_include_tag 'js/grid' %>
  <%= javascript_include_tag 'js/tile' %>
  <%= javascript_include_tag 'js/local_storage_manager' %>
  <%= javascript_include_tag 'js/game_manager' %>
  <%= javascript_include_tag 'js/application' %>
  <%= javascript_include_tag 'js1/bind_polyfill' %>
  <%= javascript_include_tag 'js1/classlist_polyfill' %>
  <%= javascript_include_tag 'js1/animframe_polyfill' %>
  <%= javascript_include_tag 'js1/keyboard_input_manager' %>
  <%= javascript_include_tag 'js1/html_actuator' %>
  <%= javascript_include_tag 'js1/tile' %>
  <%= javascript_include_tag 'js1/local_storage_manager' %>
  <%= javascript_include_tag 'js1/game_manager' %>
  <%= javascript_include_tag 'js1/application' %>
  <script type="text/javascript">
function goToPage(url)
 {
  //debugger
 // console.log(url.value);
 //if (url != "")
 //{
 	//alert('working');
 window.location.href=url.value;
 //}
 }
  </script>


  <link href="/assets/style/main.css" rel="stylesheet" type="text/css">
  <link rel="shortcut icon" href="favicon.ico">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
</head>
<body>
<div id="menu">
  <p class="menu"><%= link_to 'Blog', controller: 'blogs' %></p>
  <p class="menu"><a href=<%= home_path%>>Home</a></p>
  <p class="menu"><a href=<%= aboutme_path %>>About Me</a></p>
  <p class="menu"><a href=<%= contactme_path %>>Contact me</a></p>
  <p class="menu"><a href=<%= technology_path %>>Technologies</a></p>
  <p class="menu">
  	<select onchange="goToPage(this)">
      <option selected>Game</option>
  		<option value=<%= game_2048_path %>>2058</option>
  		<option value=<%= game_2548_path %>>2458</option>
  		<option value=<%= game_color_flood_path %>>Color-Flood</option>
  	</select>
  </p>
  
</div>
<%= yield %>

</body>
</html>